WrenchIt/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using WrenchIt.Data;
using WrenchIt.Data.RepositoryBase.IRepository;
using WrenchIt.Models;

namespace WrenchIt.Controllers
{
    [Authorize(Roles = "Customer")]
    public class CarController : Controller
    {
        private readonly IRepoWrapper _context;
        private readonly IWebHostEnvironment _hostEnvironment;



        public CarController(IRepoWrapper context, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _context = context;
        }
        public IActionResult Index()
        {

            var data = _context.Car.GetAll();
            return View(data);
        }

        public IActionResult Edit(int? id)
        {
            var car = new Car();


            if (id != null)
            {
                car = _context.Car.Get(id.GetValueOrDefault());
            }
            return View(car);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (car.Id == 0)
                {
                    //new service service type
                    var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                    var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
                    var userId = claim.Value;

                    var custId = _context.Customer.GetByUserId(userId).Id;
                    car.CustomerId = custId;
                    _context.Car.Add(car);
                }
                else
                {
                    //edit service

                    _context.Car.Update(car);
                }
                _context.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(car);
            }
        }

    }
}

WrenchIt/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WrenchIt.Data;
using WrenchIt.Data.RepositoryBase.IRepository;
using WrenchIt.Models;

namespace WrenchIt.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private static string baseurl = "https://localhost:44361/api";
        private static HttpClient client = new HttpClient();
        private readonly IRepoWrapper _newContext;
        private readonly IWebHostEnvironment _hostEnvironment;

        public CustomersController(IRepoWrapper newContext, IWebHostEnvironment hostEnvironment, ApplicationDbContext context)
        {
            _context = context;
            _newContext = newContext;
            _hostEnvironment = hostEnvironment;
        }


        // GET: Customers
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Customer"))
            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
                var userId = claim.Value;
                List<Customer> cust = new List<Customer>();
                var loggedInCustomer = _newContext.Customer.GetByUserId(userId);

                cust.Add(loggedInCustomer);

                return View(cust);
            }
            var customers = _newContext.Customer.GetAll();
            return View(customers);
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }


        public IActionResult ServiceRequests(int? id)
        {
            var uri = baseurl + "/services/GetServiceRequestByCustomerId/" + id;
            object data = null;
            try
            {
                var responseTask = client.GetAsync(uri).Result;
                data = responseTask.Content.ReadAsStringAsync().Result;

            }
            catch (Exception exception)
            {
                data = exception;
            }

            dynamic response = JsonConvert.DeserializeObject(data.ToString());
            List<ServiceRequest> results = response.ToObject<List<ServiceRequest>>();
            var viewModel = new List<ServiceRequestViewModel>();

            foreach (var item in results)
            {
                var model = viewModel.FirstOrDefault();

                model = new ServiceRequestViewModel
                {
                    Id = item.Id,
                    ServiceId = item.ServiceId,
                    Name = _newContext.Service.Get(item.ServiceId).Name,
                    Customer = _newContext.Customer.Get(item.CustomerId).FirstName,
                    Quote = item.PriceQuotation,
                    IsCompleted = item.IsCompleted,
                    CreatedAt = item.CreatedAt
                };
                viewModel.Add(model);
            }
            return View(viewModel);
        }

        public IActionResult CreateServiceRequest()
        {
            var viewModel = new CServiceRequestViewModel()
            {
                Service = new Models.Service(),
                ServiceList = _newContext.Service.GetAll()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateServiceRequest(ServiceRequest request)
        {
            var service = _newContext.Service.Get(request.Id);
            if (ModelState.IsValid)
            {
                return (RedirectToAction("ApproveServiceRequest", service));
            }
            return View(service);
        }
        public double CalculateQuote(int serviceId)
        {
            var service = _newContext.Service.GetServiceWithType(serviceId);
            double quote;

            if (service.ServiceType.Category == Category.Maintenance)
            {
                quote = service.ServiceType.Rate * 2;
            }
            else
            {
                quote = service.ServiceType.Rate * 5;
            }
            return quote;
        }
        public IActionResult ApproveServiceRequest(Service service)
        {
            var viewModel = new ApproveServiceViewModel()
            {
                Service = _newContext.Service.GetServiceWithType(service.Id),
                Quote = CalculateQuote(service.Id)
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Approve(IFormCollection formControll)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var userId = claim.Value;
            var id = formControll["serviceId"];
            var service = _newContext.Service.Get(Convert.ToInt32(id));


            var serviceRequest = new ServiceRequest()
            {
                ServiceId = service.Id,
                CustomerId = _newContext.Customer.GetByUserId(userId).Id,
                PriceQuotation = CalculateQuote(service.Id),
                CreatedAt = DateTime.Now,
                IsCompleted = false
            };

            if (ModelState.IsValid)
            {
                object output = null;
                var url = baseurl + "/services/PostService";
                var jsonObject = JsonConvert.SerializeObject(serviceRequest);
                HttpContent c = new StringContent(jsonObject, System.Text.Encoding.UTF8, "application/json");

                try
                {
                    var responseTask = client.PostAsync(url, c).Result;
                    output = responseTask.Content.ReadAsStringAsync().Result;
                }
                catch (Exception exception)
                {
                    output = exception;
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(formControll);
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Customer customer)
        {
            if (ModelState.IsValid)

            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
                var userId = claim.Value;

                customer.IdentityUserId = userId;
                _context.Customers.Add(customer);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", customer.IdentityUserId);
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", customer.IdentityUserId);
            return View(customer);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Address,City,State,ZipCode,Car,IdentityUserId")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", customer.IdentityUserId);
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

WrenchIt/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using WrenchIt.Data.RepositoryBase.IRepository;
using WrenchIt.Models;

namespace WrenchIt.Controllers
{
    [Authorize(Roles = "Employee")]
    public class ServicesController : Controller
    {

        private readonly IRepoWrapper _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        //public IEnumerable<SelectListItem> CategoryList { get; set; }
        public ServicesController(IRepoWrapper context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }
        // GET: Service
        public IActionResult Index()
        {
            var serviceList = _context.Service.GetAllServices();
            return View(serviceList);
        }
        [HttpGet]
        public IActionResult GetAll()
        {
            var data = _context.Service.GetAllServices();
            return Json(new { data = _context.Service.GetAllServices() });
        }
        public IActionResult Edit(int? id)
        {
            ServiceViewModel serviceViewModel = new ServiceViewModel()
            {
                Service = new Models.Service(),
                ServiceTypeList = _context.ServiceType.GetAll()
            };


            if (id != null)
            {
                serviceViewModel.Service = _context.Service.Get(id.GetValueOrDefault());
            }
            return View(serviceViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Service service)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (service.Id == 0)
                {
                    //new service
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"images\servicePics");
                    var extension = Path.GetExtension(files[0].FileName);
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    service.ImageUrl = @"\images\servicePics" + fileName + extension;
                    _context.Service.Add(service);
                }
                else
                {
                    //edit service
                    var serviceFromDb = _context.Service.Get(service.Id);
                    if (files.Count > 0)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        var uploads = Path.Combine(webRootPath, @"images\servicePics");
                        var newExtension = Path.GetExtension(files[0].FileName);
                        var imagePath = Path.Combine(webRootPath, serviceFromDb.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                        using (var fileStream = new FileStream(Path.Combine(uploads, fileName + newExtension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }
                        service.ImageUrl = @"\images\servicePics\" + fileName + newExtension;
                    }
                    else
                    {
                        service.ImageUrl = serviceFromDb.ImageUrl;
                    }
                    _context.Service.Update(service);
                }
                _context.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(service);
            }
        }
        // GET: Service/Delete/5
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var serviceFromDB = _context.Service.Get(id);
            string webRootPath = _hostEnvironment.WebRootPath;
            var imagePath = Path.Combine(webRootPath, serviceFromDB.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }
            if (serviceFromDB == null)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }
            _context.Service.Remove(serviceFromDB);
            _context.Save();
            return Json(new { success = true, message = "Delete successful." });
        }
        // POST: Service/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WrenchIt/Views/Shared/_CreateBacktoList.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

WrenchIt/Views/Shared/_EditBacktoList.cshtml
@model int


<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

WrenchIt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wrench It</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wrench It</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Managment
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropDown">
                                @if (User.IsInRole("Employee"))
                                {
                                    <a class="dropdown-item text-white " asp-controller="Services" asp-action="Index">Services</a>
                                    <a class="dropdown-item text-white " asp-controller="Customers" asp-action="Index">Customers</a>
                                    <a class="dropdown-item text-white " asp-controller="ServiceType" asp-action="Index">ServiceType</a>
                                    <a class="dropdown-item text-white " asp-controller="ServiceRequest" asp-action="Index">service request</a>
                                }
                                @if (User.IsInRole("Customer"))
                                {
                                    <a class="dropdown-item text-white " asp-controller="Car" asp-action="Index">Car Management</a>
                                    <a class="dropdown-item text-white " asp-controller="Customers" asp-action="CreateServiceRequest">Service Request</a>
                                    <a class="dropdown-item text-white " asp-controller="Customers" asp-action="Index">Customers</a>


                                }
                            </div>

                    </ul>
                }
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container my-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Wrench It
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/c5f54c2a2e.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>